//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trees.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                ,@@@@@@@,
        ///       ,,,.   ,@@@@@@/@@,  .oo8888o.
        ///    ,&amp;%%&amp;%&amp;&amp;%,@@@@@/@@@@@@,8888\\88/8o
        ///   ,%&amp;\\%&amp;&amp;%&amp;&amp;%,@@@\\@@@/@@@88\\88888/88&apos;
        ///   %&amp;&amp;%&amp;%&amp;/%&amp;&amp;%@@\\@@/ /@@@88888\\88888&apos;
        ///   %&amp;&amp;%/ %&amp;%%&amp;&amp;@@\\ V /@@&apos; `88\\8 `/88&apos;
        ///   `&amp;%\\ ` /%&amp;&apos;    |.|        \\ &apos;|8&apos;
        ///       |o|        | |         | |
        ///       |.|        | |         | |
        ///jgs \\/ ._\\//_/__/  ,\\_//__\\/.  \\_//__/_.
        /// </summary>
        internal static string treeAsciiArt {
            get {
                return ResourceManager.GetString("treeAsciiArt", resourceCulture);
            }
        }
    }
}
